import '../styles/globals.css'
import Head from 'next/head'
import NavBar from '../component/NavBar'
import Menu from '../component/Bar'
import Provider from '../providers/user'
import "react-responsive-modal/styles.css";
import { ToastProvider } from "react-toast-notifications";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Provider>
        <Head>
          <title>Bitcomer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet"></link>

        </Head>

        <div className="h-windows flex w-full ">
          <ToastProvider autoDismiss={true} newestOnTop={true}>
            <Component {...pageProps} />
          </ToastProvider>
        </div>


      </Provider>


    </>

  )
}

export default MyApp
